"""
Tests for the private-companies seed pipeline.

Covers the three deliverables required by the task brief:
1. Wikipedia loader returns 600+ rows including Anthropic / OpenAI / SpaceX / Stripe.
2. Merge correctly disambiguates Canva (Wikipedia) from CANVA AUSTRALIA HOLDINGS PTY LTD
   (N-PORT title), linking the latter via the manual alias table.
3. Wiz is flagged is_acquired=True with lifecycle_status='acquired'.

Plus a few correctness/sanity tests for normalization and alias rollup.

Network behavior
----------------
The Wikipedia loader test calls the live Wikipedia API. If `PFR_OFFLINE=1` is
set in the environment, those tests are skipped (e.g. for CI on an air-gapped
runner). All non-network tests run unconditionally.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from nport.seed_loader import load_seed_supabase, merge_and_emit, wikipedia_loader

DATA_DIR = Path(__file__).resolve().parent.parent
OFFLINE = os.environ.get("PFR_OFFLINE") == "1"


# ----------------------------------------------------------------------------
# Wikipedia loader
# ----------------------------------------------------------------------------
@pytest.fixture(scope="module")
def wikipedia_entries():
    """Live call to the Wikipedia API — cached for the whole module."""
    if OFFLINE:
        pytest.skip("PFR_OFFLINE=1 — skipping live Wikipedia API test.")
    return wikipedia_loader.load_unicorns()


def test_wikipedia_returns_600_plus_rows(wikipedia_entries):
    """The plan §6.7 quotes 618 active + 206 exited; we tolerate ±50 row drift."""
    assert len(wikipedia_entries) >= 600, (
        f"Expected 600+ unicorn rows from Wikipedia; got {len(wikipedia_entries)}"
    )


@pytest.mark.parametrize("target", ["Anthropic", "OpenAI", "SpaceX", "Stripe"])
def test_wikipedia_contains_key_companies(wikipedia_entries, target):
    """Each named company must appear at least once in the parsed output."""
    hits = [e for e in wikipedia_entries if e.company.lower() == target.lower()]
    assert hits, f"Wikipedia loader missed '{target}'"
    e = hits[0]
    assert e.valuation_usd_billions and e.valuation_usd_billions > 0, (
        f"{target} has no valuation"
    )


def test_wikipedia_emits_active_and_exited_tables(wikipedia_entries):
    active = [e for e in wikipedia_entries if e.table == "active"]
    exited = [e for e in wikipedia_entries if e.table == "exited"]
    assert len(active) >= 500, f"too few active rows: {len(active)}"
    assert len(exited) >= 150, f"too few exited rows: {len(exited)}"
    # Uber should appear in exited (IPO 2019)
    uber = next((e for e in exited if e.company.lower() == "uber"), None)
    assert uber is not None, "Uber missing from exited table"


# ----------------------------------------------------------------------------
# Name normalization
# ----------------------------------------------------------------------------
@pytest.mark.parametrize("raw,expected", [
    ("Anthropic PBC", "ANTHROPIC"),
    ("Anthropic, Inc.", "ANTHROPIC"),
    ("ANTHROPIC PBC SERIES F PC PP", "ANTHROPIC PBC SERIES F PC PP"),  # no legal suffix to strip
    ("Space Exploration Technologies Corp.", "SPACE EXPLORATION TECHNOLOGIES"),
    ("Stripe, Inc.", "STRIPE"),
    ("Canva Pty Ltd", "CANVA"),
    ("CANVA AUSTRALIA HOLDINGS PTY LTD", "CANVA AUSTRALIA"),
    ("Tiger Fund, L.P.", "TIGER FUND"),
])
def test_normalize_name(raw, expected):
    assert merge_and_emit.normalize_name(raw) == expected


def test_slugify():
    assert merge_and_emit.slugify("Anthropic, Inc.") == "anthropic-inc"
    assert merge_and_emit.slugify("OpenAI") == "openai"
    assert merge_and_emit.slugify("Space Exploration Technologies") == "space-exploration-technologies"


# ----------------------------------------------------------------------------
# Merge pipeline
# ----------------------------------------------------------------------------
@pytest.fixture(scope="module")
def merged():
    """Run merge_and_emit against the seed JSONs in this dir.

    Wikipedia file may have been generated by an earlier test run / manual run.
    If absent and we're online, we generate it here.
    """
    wiki_path = DATA_DIR / "wikipedia_unicorns.json"
    if not wiki_path.exists():
        if OFFLINE:
            pytest.skip("Wikipedia seed missing and PFR_OFFLINE=1.")
        wikipedia_loader.main([])  # populates the default output path
    wikipedia = merge_and_emit.load_json(wiki_path)
    wikidata = merge_and_emit.load_json(DATA_DIR / "wikidata_enriched.json")
    nport = merge_and_emit.load_json(DATA_DIR / "nport_clusters.json")
    manual = merge_and_emit.load_json(DATA_DIR / "manual_curated_seed.json")
    lifecycle = merge_and_emit.load_json(DATA_DIR / "lifecycle_flags.json")
    companies = merge_and_emit.build_companies(wikipedia, wikidata, nport, manual, lifecycle)
    aliases = merge_and_emit.build_aliases(companies, manual)
    return companies, aliases


def test_merge_produces_canva_with_nport_alias(merged):
    """
    Canva is in the Wikipedia list as 'Canva' (Australia), but the N-PORT-discovered
    raw title is 'CANVA AUSTRALIA HOLDINGS PTY LTD'. The manual seed must encode
    an alias that lets the resolution pipeline match the N-PORT string to the
    Wikipedia entry's slug.
    """
    companies, aliases = merged
    assert "canva" in companies, "canva slug missing from merged companies"
    canva = companies["canva"]
    assert canva["display_name"] == "Canva", (
        f"Canva display_name unexpected: {canva['display_name']!r}"
    )

    # Aliases for canva
    canva_aliases = [a for a in aliases if a["company_slug"] == "canva"]
    assert canva_aliases, "no aliases for canva"

    # One alias must match the normalized form of the N-PORT raw title.
    nport_raw = "CANVA AUSTRALIA HOLDINGS PTY LTD"
    nport_norm = merge_and_emit.normalize_name(nport_raw)
    assert nport_norm == "CANVA AUSTRALIA", f"normalization changed: {nport_norm!r}"

    matching = [
        a for a in canva_aliases
        if a["pattern_type"] == "exact_normalized"
        and a["pattern"] == nport_norm
    ]
    assert matching, (
        "Expected an exact_normalized alias for 'CANVA AUSTRALIA' linking "
        "the N-PORT subsidiary title to the canva slug. Aliases: "
        f"{[a['pattern'] for a in canva_aliases]}"
    )


def test_wiz_is_acquired(merged):
    """Wiz must be flagged as acquired by Google."""
    companies, _ = merged
    assert "wiz" in companies, "wiz missing from merged companies"
    wiz = companies["wiz"]
    assert wiz["is_acquired"] is True, f"Wiz is_acquired wrong: {wiz['is_acquired']}"
    assert wiz["lifecycle_status"] == "acquired", (
        f"Wiz lifecycle_status wrong: {wiz['lifecycle_status']}"
    )
    assert "google" in (wiz["acquired_by"] or "").lower(), (
        f"Wiz acquired_by wrong: {wiz['acquired_by']}"
    )


def test_anthropic_has_full_alias_set(merged):
    """Manual seed should produce the documented alias rows.

    The task brief listed `ANTHROPIC PBC` as an exact_normalized example,
    but `PBC` is a legal-entity suffix that our normalize_name() strips, so
    by the time the alias hits the database both `ANTHROPIC` and
    `ANTHROPIC PBC` collapse to the same row — which is the correct
    behavior because the resolution pipeline will also normalize the
    incoming N-PORT string. We therefore check the post-normalization
    invariants instead of the pre-normalization examples.
    """
    _, aliases = merged
    ant = [a for a in aliases if a["company_slug"] == "anthropic"]
    patterns = {(a["pattern_type"], a["pattern"]) for a in ant}
    assert ("exact_normalized", "ANTHROPIC") in patterns
    assert ("prefix", "ANTHROPIC") in patterns
    assert any(
        a["pattern_type"] == "vendor_code"
        and a["vendor_code_type"] == "BlackRock"
        for a in ant
    ), "missing BlackRock vendor_code alias for Anthropic"

    # Sanity: the raw manual seed must still have included ANTHROPIC PBC
    # as a value the curator typed in (it just got normalized on emit).
    manual_path = DATA_DIR / "manual_curated_seed.json"
    raw = json.loads(manual_path.read_text())
    ant_entry = next(e for e in raw["entries"] if e["slug"] == "anthropic")
    raw_patterns = {a["pattern"] for a in ant_entry["aliases"]}
    assert "ANTHROPIC PBC" in raw_patterns, (
        "Curator-typed manual seed should retain 'ANTHROPIC PBC' verbatim"
    )


def test_aliases_have_required_fields(merged):
    """Every alias must have company_slug, pattern_type, pattern, exposure_type, source."""
    _, aliases = merged
    required = {"company_slug", "pattern_type", "pattern", "exposure_type", "source"}
    valid_pt = {"exact_normalized", "prefix", "contains", "regex", "vendor_code"}
    valid_et = {"direct", "spv", "feeder", "derivative", "credit"}
    for a in aliases:
        missing = required - set(a)
        assert not missing, f"alias missing fields {missing}: {a}"
        assert a["pattern_type"] in valid_pt, f"bad pattern_type: {a}"
        assert a["exposure_type"] in valid_et, f"bad exposure_type: {a}"
        assert a["pattern"].strip(), f"empty pattern: {a}"


def test_no_duplicate_aliases(merged):
    """No (slug, pattern_type, pattern) triple should appear twice."""
    _, aliases = merged
    seen = set()
    for a in aliases:
        key = (a["company_slug"], a["pattern_type"], a["pattern"])
        assert key not in seen, f"duplicate alias: {key}"
        seen.add(key)


# ----------------------------------------------------------------------------
# Sanctioned seed sanity
# ----------------------------------------------------------------------------
def test_sanctioned_seed_targets_correct_table():
    """The sanctioned seed must NOT be loaded into private_companies."""
    raw = json.loads((DATA_DIR / "sanctioned_seed.json").read_text())
    assert raw.get("_target_table") == "sanctioned_securities"
    assert raw.get("_NOT_in_table") == "private_companies"
    assert len(raw["entries"]) >= 15, "sanctioned list suspiciously small"
    # Sberbank must be there
    patterns = [e["pattern"] for e in raw["entries"]]
    assert "SBERBANK" in patterns
    assert "LUKOIL" in patterns


def test_supabase_seed_loader_validates_default_payload():
    """Live loader dry-run should accept the checked-in seed payload."""
    companies, aliases, dropped_dates = load_seed_supabase.build_seed_payload(DATA_DIR)
    assert len(companies) == 843
    assert len(aliases) == 924
    assert dropped_dates
    assert all("company_id" in alias for alias in aliases)
    assert next(c for c in companies if c["slug"] == "anthropic")["display_name"] == "Anthropic"


def test_supabase_seed_loader_drops_ambiguous_dates_without_false_precision():
    """Month-only lifecycle dates should not become fake first-of-month dates."""
    assert load_seed_supabase.normalize_date("2026-05-11") == "2026-05-11"
    assert load_seed_supabase.normalize_date("December 2020") is None
    assert load_seed_supabase.normalize_date(None) is None


# ----------------------------------------------------------------------------
# nport_clusters sanity
# ----------------------------------------------------------------------------
def test_nport_clusters_has_50_with_sectors():
    raw = json.loads((DATA_DIR / "nport_clusters.json").read_text())
    assert len(raw["clusters"]) >= 50
    valid_sectors = {"ai_ml", "space_defense", "fintech", "biotech", "consumer", "mobility", "other"}
    for c in raw["clusters"]:
        assert c["sector"] in valid_sectors, f"bad sector: {c}"
        assert c["proposed_company_slug"], f"missing slug: {c}"
        assert isinstance(c["raw_titles"], list) and c["raw_titles"], f"missing raw_titles: {c}"
